export const RECV_ERROR = 'RECV_ERROR';
export const REQ_DATA = 'REQ_DATA';
export const RECV_DATA = 'RECV_DATA';

export const TOWNSHIP_EDIT_PUT_REQ = 'TOWNSHIP_EDIT_PUT_REQ';
export const TOWNSHIP_EDIT_PUT_SUCCESS = 'TOWNSHIP_EDIT_PUT_SUCCESS';
export const TOWNSHIP_EDIT_PUT_ERROR = 'TOWNSHIP_EDIT_PUT_ERROR';


export const FETCH_TOWNSHIP_LIST = 'FETCH_TOWNSHIP_LIST';
export const SUBMIT_NEW_TOWNSHIP = 'SUBMIT_NEW_TOWNSHIP';
