export const TOWNSHIP_FETCH_GET_REQ = 'TOWNSHIP_FETCH_GET_REQ';
export const TOWNSHIP_FETCH_GET_SUCCESS = 'TOWNSHIP_FETCH_GET_SUCCESS';
export const TOWNSHIP_FETCH_GET_ERROR = 'TOWNSHIP_FETCH_GET_ERROR';

export const DETAILS_FETCH_GET_REQ = 'DETAILS_FETCH_GET_REQ';
export const DETAILS_FETCH_GET_SUCCESS = 'DETAILS_FETCH_GET_SUCCESS';
export const DETAILS_FETCH_GET_ERROR = 'DETAILS_FETCH_GET_ERROR';

export const TOWNSHIP_EDIT_PUT_REQ = 'TOWNSHIP_EDIT_PUT_REQ';
export const TOWNSHIP_EDIT_PUT_SUCCESS = 'TOWNSHIP_EDIT_PUT_SUCCESS';
export const TOWNSHIP_EDIT_PUT_ERROR = 'TOWNSHIP_EDIT_PUT_ERROR';

export const TOWNSHIP_CREATE_POST_REQ = 'TOWNSHIP_CREATE_POST_REQ';
export const TOWNSHIP_CREATE_POST_SUCCESS = 'TOWNSHIP_CREATE_POST_SUCCESS';
export const TOWNSHIP_CREATE_POST_ERROR = 'TOWNSHIP_CREATE_POST_ERROR';

export const UPLOAD_TOWNSHIP_IMAGE_REQ = 'UPLOAD_TOWNSHIP_IMAGE_REQ';
export const UPLOAD_TOWNSHIP_IMAGE_SUCCESS = 'UPLOAD_TOWNSHIP_IMAGE_SUCCESS';
export const UPLOAD_TOWNSHIP_IMAGE_ERROR = 'UPLOAD_TOWNSHIP_IMAGE_ERROR';


export const RESET_LOADING = 'RESET_LOADING';

// Township Panel

export const TOWNSHIP_USERS_GET_REQ = 'TOWNSHIP_USERS_GET_REQ';
export const TOWNSHIP_USERS_GET_SUCCESS = 'TOWNSHIP_USERS_GET_SUCCESS';
export const TOWNSHIP_USERS_GET_ERROR = 'TOWNSHIP_USERS_GET_ERROR';

export const TOWNSHIP_USERS_PUT_REQ = 'TOWNSHIP_USERS_PUT_REQ';
export const TOWNSHIP_USERS_PUT_SUCCESS = 'TOWNSHIP_USERS_PUT_SUCCESS';
export const TOWNSHIP_USERS_PUT_ERROR = 'TOWNSHIP_USERS_PUT_ERROR';

export const TOWNSHIP_USERS_POST_REQ = 'TOWNSHIP_USERS_POST_REQ';
export const TOWNSHIP_USERS_POST_SUCCESS = 'TOWNSHIP_USERS_POST_SUCCESS';
export const TOWNSHIP_USERS_POST_ERROR = 'TOWNSHIP_USERS_POST_ERROR';
