export const TOWNSHIP_FETCH_GET_REQ = 'TOWNSHIP_FETCH_GET_REQ';
export const TOWNSHIP_FETCH_GET_SUCCESS = 'TOWNSHIP_FETCH_GET_SUCCESS';
export const TOWNSHIP_FETCH_GET_ERROR = 'TOWNSHIP_FETCH_GET_ERROR';

export const TOWNSHIP_EDIT_PUT_REQ = 'TOWNSHIP_EDIT_PUT_REQ';
export const TOWNSHIP_EDIT_PUT_SUCCESS = 'TOWNSHIP_EDIT_PUT_SUCCESS';
export const TOWNSHIP_EDIT_PUT_ERROR = 'TOWNSHIP_EDIT_PUT_ERROR';

export const TOWNSHIP_CREATE_POST_REQ = 'TOWNSHIP_CREATE_POST_REQ';
export const TOWNSHIP_CREATE_POST_SUCCESS = 'TOWNSHIP_CREATE_POST_SUCCESS';
export const TOWNSHIP_CREATE_POST_ERROR = 'TOWNSHIP_CREATE_POST_ERROR';

export const RESET_LOADING = 'RESET_LOADING';
