export const AUTH_INITIATE = "AUTH_INITIATE";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const REG_INITIATE = "REG_INITIATE";
export const REG_SUCCESS = "REG_SUCCESS";
export const REG_FAIL = "REG_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const PLATE_ADDITION_INITIATE = "PLATE_ADDITION_INITIATE";
export const PLATE_ADDITION_SUCCESS = "PLATE_ADDITION_SUCCESS";
export const PLATE_ADDITION_FAIL = "PLATE_ADDITION_FAIL";

export const FETCH_VEHICLES_INITIATE = "FETCH_VEHICLES_INITIATE";
export const FETCH_VEHICLES_SUCCESS = "FETCH_VEHICLES_SUCCESS";
export const FETCH_VEHICLES_FAIL = "FETCH_VEHICLES_FAIL";

