export const AUTH_INITIATE = "AUTH_INITIATE";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const REG_INITIATE = "REG_INITIATE";
export const REG_SUCCESS = "REG_SUCCESS";
export const REG_FAIL = "REG_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT";

export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION";

export const PLATE_ADDITION_INITIATE = "PLATE_ADDITION_INITIATE";
export const PLATE_ADDITION_SUCCESS = "PLATE_ADDITION_SUCCESS";
export const PLATE_ADDITION_FAIL = "PLATE_ADDITION_FAIL";

export const FETCH_VEHICLE_INITIATE = "FETCH_VEHICLE_INITIATE";
export const FETCH_VEHICLE_SUCCESS = "FETCH_VEHICLE_SUCCESS";
export const FETCH_VEHICLE_FAIL = "FETCH_VEHICLE_FAIL";

export const FETCH_VEHICLES_INITIATE = "FETCH_VEHICLES_INITIATE";
export const FETCH_VEHICLES_SUCCESS = "FETCH_VEHICLES_SUCCESS";
export const FETCH_VEHICLES_FAIL = "FETCH_VEHICLES_FAIL";

export const FETCH_PARKING_INITIATE = "FETCH_PARKING_INITIATE";
export const FETCH_PARKING_SUCCESS = "FETCH_PARKING_SUCCESS";
export const FETCH_PARKING_FAIL = "FETCH_PARKING_FAIL";

export const UPDATE_GEOLOCATION = "UPDATE_GEOLOCATION";

export const TOGGLE_FREE_PARKING = "TOGGLE_FREE_PARKING";
export const TOGGLE_PAID_PARKING = "TOGGLE_PAID_PARKING";
export const TOGGLE_MANAGED_PARKING = "TOGGLE_MANAGED_PARKING";

export const FETCH_PERMITS_INITIATE = "FETCH_PERMITS_INITIATE";
export const FETCH_PERMITS_SUCCESS = "FETCH_PERMITS_SUCCESS";
export const FETCH_PERMITS_FAIL = "FETCH_PERMITS_FAIL";

export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAIL = "FETCH_LOCATIONS_FAIL";

export const FETCH_TICKETS_INITIATE = "FETCH_TICKETS_INITIATE";
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_FAIL = "FETCH_TICKETS_FAIL";

export const SET_MODAL_DATA = "SET_MODAL_DATA";

export const FETCH_LOCATION_INITIATE = "FETCH_LOCATION_INITIATE";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_FAIL = "FETCH_LOCATION_FAIL";

export const FETCH_TRANSACTION_INITIATE = "FETCH_TRANSACTION_INITIATE";
export const FETCH_TRANSACTION_SUCCESS = "FETCH_TRANSACTION_SUCCESS";
export const FETCH_TRANSACTION_FAIL = "FETCH_TRANSACTION_FAIL";
export const SET_ADDING_FUNDS = "SET_ADDING_FUNDS";

export const FETCH_WEATHER_INITIATE = "FETCH_WEATHER_INITIATE";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAIL = "FETCH_WEATHER_FAIL";
export const LOCATION_NOT_FOUND = "LOCATION_NOT_FOUND";

export const FETCH_PLACES_INITIATE = "FETCH_PLACES_INITIATE";
export const FETCH_PLACES_SUCCESS = "FETCH_PLACES_SUCCESS";
export const FETCH_PLACES_FAIL = "FETCH_PLACES_FAIL";

export const FETCH_LOCATION_DETAILS_INITIATE = "FETCH_LOCATION_DETAILS_INITIATE";
export const FETCH_LOCATION_DETAILS_SUCCESS = "FETCH_LOCATION_DETAILS_SUCCESS";
export const FETCH_LOCATION_DETAILS_FAIL = "FETCH_LOCATION_DETAILS_FAIL";
